### ISSUE TITLE
Having a problem running against Google timeline

### ISSUE THREAD

**Issue by bunk3m** [nerik/google-timeline-to-csv#3]
I downloaded quite a bit of trip data from Google to see if I could see the trips and days.  It was the standard Google data download from the link provided.

My Location History file is 460.3MB.  ?Too large?

I get the following error when I try to run this command from the /Downloads/google-timeline-to-csv-master folder:
`./index.js ../Takeout/Location\ History > my_trips.csv`

`Error: params should include "fields" and/or non-empty "data" array of objects
--
at checkParams (/Users/user/Downloads/google-timeline-to-csv-master/node_modules/json2csv/lib/json2csv.js:95:11)
at module.exports (/Users/user/Downloads/google-timeline-to-csv-master/node_modules/json2csv/lib/json2csv.js:48:5)
at pointsToCsv (/Users/user/Downloads/google-timeline-to-csv-master/index.js:134:3)
at Object.<anonymous> (/Users/user/Downloads/google-timeline-to-csv-master/index.js:39:1)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)`

What should I be trying next?

**Comment by kevinvkasundra** [comment]
Hey, how did you download the trip data? Can you please help me

**Comment by kevinvkasundra** [comment]
@bunk3m

**Comment by bunk3m** [comment]
Look in your Google account for the timeline.  In the Google account you can find a link to download all your data.  If you can't find it, go to [https://support.google.com/accounts/answer/3024190?hl=en](url)
